### ISSUE TITLE
How to customize the filename of CSV generated

### ISSUE THREAD

**Issue by coneypo** [azavea/django-queryset-csv#105]
If there is a parameter in function **render_to_csv_response()**, which I can modify the filename of CSV generated ?

```
import djqscsv
data=...
djqcsv.render_to_csv_response(data)
```

Thanks!

**Comment by maurizi** [comment]
Hi, thanks for using this library!

You can use the `filename` parameter to change the filename used in the `Content-Disposition` header.
This has been around for a while, but we've failed to document it until now. Thanks for the needed reminder to get around to that - we've now updated the README with documentation on this parameter.

**Comment by coneypo** [comment]
Thanks for your quick response😀!
