### ISSUE TITLE
Maybe, a Django-csv-load?

### ISSUE THREAD

**Issue by Eternal-127** [azavea/django-queryset-csv#107]
Hii, there I believe this is a really nicely done work and it is going to help in my work but don't you think we can also have a reverse of this which imports the data from CSV into the database. If you have some thoughts on it let me know, I am more than happy to contribute.

**Comment by maurizi** [comment]
@Eternal-127 Thanks for using this library!

I think your idea sounds valuable, but it is outside the scope of this library, which is focused solely on exports.
