### ISSUE TITLE
Django 3: Error importing six from django.utils (deprecated module)

### ISSUE THREAD

**Issue by mojo17** [azavea/django-queryset-csv#110]
django-queryset-csv fails to initialize when using Django 3 due to django.utils.six being deprecated:

    File "C:\venv\lib\site-packages\djqscsv\djqscsv.py", line 9, in <module>
        from django.utils import six
    ImportError: cannot import name 'six' from 'django.utils' (C:\venv\lib\site-packages\django\utils\__init__.py)

From [Django 3 Release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/): **django.utils.six** - Remove usage of this vendored library or switch to [six](https://pypi.org/project/six/).

**Comment by jwalgran** [comment]
This was fixed by @darkcloud1801 and included in #112. This fix has been released as version 1.1.0.
