### ISSUE TITLE
Any plan to support m2m fields?

### ISSUE THREAD

**Issue by shang-wang** [azavea/django-queryset-csv#60]
Hi azavea:

First of all, thanks for the work, it really made my life easier! However, I still wonder if you guys have any plans to support m2m fields. I know it's tricky because django's Model.objects.values() doesn't play very well with m2m fields, and it's also tricky to handle which field in the m2m model you want to use for display. If you guys have some thoughts about it, like putting together the unicode for each m2m entry, etc, please let me know. Thanks!

**Comment by nabinkhadka** [comment]
Any way of specifying number of items only? Like in above example one could choose "Kathmandu" and "Pokhara" (cities from Nepal), and then the result could be "2"? That might be easier? If so, how?
