### ISSUE TITLE
djqscsv Fails with Django 1.9

### ISSUE THREAD

**Issue by shinyarc** [azavea/django-queryset-csv#78]
Django 1.9 got rid of ValuesQuerySet which causes errors when djqscsv attempts to import it.

**Comment by avelis** [comment]
@shinyarc It looks like ValuesQuerySet has been removed in Django 1.9. I couldn't find an equivalent except for ValuesIterable.

So, I guess one pull request would be to import ValuesQuerySet or ValuesIterable if Django 1.9 or higher.

**Comment by adonm** [comment]
Have done a bit of related work in #80 though there is a little regression around verbose names

**Comment by luanfonceca** [comment]
How is the progress of this and how can i help?
I need to upgrade to 1.9 too.


o/

**Comment by steventlamb** [comment]
We (the maintainers) have plans to add support for Django 1.9, but a timeline is not established. Some internal aspects of the Values/QuerySet API that djqscsv made use of have changed, so it's not a trivial fix.

**Comment by steventlamb** [comment]
Django 1.9 is officially supported as of https://github.com/azavea/django-queryset-csv/releases/tag/0.3.3
