### ISSUE TITLE
Strange characters in ID column title, with MS Excel

### ISSUE THREAD

**Issue by Jakobovski** [azavea/django-queryset-csv#94]
I setup a toy view per the documentation. It works great except for one thing.

In the CSV file the `ID` column has some strange characters in it. See screenshot.
 
![Screenshot](https://www.dropbox.com/s/nlsefw0sg9wml57/Screenshot%202017-01-18%2021.07.02.png?raw=1 )

It seems like the issue is related to Microsoft Excel, because if i open the file in a text editor everything looks fine

**Comment by RickMohr** [comment]
It's a bug with Mac Excel, which incorrectly shows that when opening a CSV using UTF-8 encoding (which django-queryset-csv produces).

**Comment by maurizi** [comment]
For more information, please see the discussion on this issue https://github.com/azavea/django-queryset-csv/issues/71 as well as http://stackoverflow.com/questions/6588068/which-encoding-opens-csv-files-correctly-with-excel-on-both-mac-and-windows
