### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Jakobovski** [azavea/django-queryset-csv#95]
It would be great if the library would support writing `lists` to csv. 

Something like this:

> header = [...]
> data = [[], [], []]
> 
> render_to_csv_response(data, header=header)

**Comment by maurizi** [comment]
Thanks for your input! While this proposed could certainly be a useful feature, I don't think it's the right fit for this library.

As the name implies, this library is squarely focused on turning _QuerySets_ into CSVs, and is not a general-purpose CSV library.
