### ISSUE TITLE
Following example in README doesn't work on Python 3.5 environment.

### ISSUE THREAD

**Issue by Asayu123** [azavea/django-queryset-csv#98]
It looks like Following example at Usage section in README causes error on python3.5 environment.

### Target Code
```
If you need to write the CSV to a file you can use write_csv instead:

from djqscsv import write_csv

qs = Foo.objects.filter(bar=True).values('id', 'bar')
with open('foo.csv', 'w') as csv_file:
  write_csv(qs, csv_file)
```

### RESULT
```
TypeError: write() argument must be str, not bytes
```
write_csv method trying to write byte (BOM) to file, so We need to open file as binary mode.

### Correct Example
```
with open('foo.csv', 'wb') as csv_file:
  write_csv(qs, csv_file)
```

I'm glad if you test those examples in your environment and confirm whether correction works.
Kind Regards,
Asayu123

**Comment by maurizi** [comment]
Thanks for the feedback!

You're totally correct :smile: 
This library has been most thoroughly battle-tested on Python 2, so I think this one just slipped through the cracks.

The README has been updated to reflect your feedback.
